name: pull-info

on:
  push:
    branches: [ "main" ]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo ${{ github.event.push.GITHUB_REF }}
