name: pull-info

on:
  push:
    branches: [ "main" ]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: echo "'${{ github.ref_name }}' was pushed by '${{ github.actor }}'"
