name: show-push-info

on:
  push:

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
    
      - name: Print info
        run: echo "'${{ github.ref_name }}' was pushed by '${{ github.event.pusher.name }}'"
#
